# Generated by Django 4.0.2 on 2022-02-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
