# Generated by Django 4.0.2 on 2022-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_of_product',
            field=models.CharField(max_length=100, verbose_name='Наименование продукта'),
        ),
    ]
