# Generated by Django 4.0.2 on 2022-02-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0003_alter_product_title_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_of_kg',
            field=models.FloatField(verbose_name='Цена за 1 кг(л)'),
        ),
    ]
