# Generated by Django 4.0.2 on 2022-02-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0004_alter_product_price_of_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_kg_product',
            field=models.FloatField(verbose_name='Количество(кг\\л)'),
        ),
    ]
