# Generated by Django 4.0.2 on 2022-02-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0006_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_of_kg',
            field=models.FloatField(verbose_name='Цена (руб) за 1 кг(л)'),
        ),
    ]
