# Generated by Django 4.0.2 on 2022-02-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0008_alter_product_options_alter_product_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
    ]
