# Generated by Django 4.0.2 on 2022-02-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0010_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Срок годности (количество суток)'),
        ),
    ]
