# Generated by Django 4.0.2 on 2022-03-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0011_alter_product_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='deliveries',
            field=models.ManyToManyField(to='store_mng.Delivery'),
        ),
    ]
