# Generated by Django 4.0.2 on 2022-03-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0012_delivery_product_deliveries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deliveries',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
