# Generated by Django 4.0.2 on 2022-03-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0013_remove_product_deliveries_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_of_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store_mng.category_of_product'),
        ),
    ]
