# Generated by Django 4.0.2 on 2022-03-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_mng', '0014_category_of_product_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_of_product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория продукта'),
        ),
    ]
